name: Lint Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Lint-Check:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Lint Check
        uses: super-linter/super-linter@v8.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.LINT_TOKEN }}
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: false
          IGNORE_GITIGNORED_FILES: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_JAVASCRIPT_PRETTIER: true
          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_TYPESCRIPT_PRETTIER: true
          VALIDATE_JSON: true
          VALIDATE_JSON_PRETTIER: true
          VALIDATE_JSX: true
          VALIDATE_JSX_PRETTIER: true
          VALIDATE_TSX: true
          VALIDATE_MARKDOWN: true
          VALIDATE_MARKDOWN_PRETTIER: true
