name: Spelling Action

on:
  pull_request:
    branches: [ "main" ]

env:
  CLICOLOR: 1
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  Spelling-Check:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Spell Check with Typos
        uses: crate-ci/typos@v1.36.2
        with:
          isolated: true
