name: Spelling Check

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  CLICOLOR: 1

jobs:
  Spelling-Check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Spell Check with Typos
        uses: crate-ci/typos@v1.36.2
        with:
          isolated: true
